name: publish-docker

on: 
  schedule:
    - cron: '* 0 * * *'
  workflow_dispatch:

jobs:
  publish-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Origin Repo
        uses: actions/checkout@v2
        with:
          repository: 'miyouzi/aniGamerPlus'
          path: 'aniGamerPlus'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: tonypepe/anigamerplus:latest
          context: 'aniGamerPlus'
